### ISSUE TITLE
Symbolizer.normalize fails if value === min && max === min

### ISSUE THREAD

**Issue by kordilery** [gis4dis/cg#12]
In [normalize function](https://github.com/gis4dis/cg/blob/master/src/cg/symbolizers/Symbolizer.js#L52), if value === min && max === min, the first part of expression is evaluated as 0 / 0 and the function returns NaN.

**Comment by Bulva** [comment]
Fixed (fa63199fa580a6a57b5207fea0786b441ad81155). The mean value is used when max === min
