### ISSUE TITLE
Saving style in feature (combinedSymbol) does not work for MC-client

### ISSUE THREAD

**Issue by kordilery** [gis4dis/cg#13]
Features in a layer source are updated based on id - see [code](https://github.com/gis4dis/mc-client/blob/master/components/Map.js#L253)
In a newer version, CG stores **combinedSymbol** to derive current style [directly in the feature](https://github.com/gis4dis/cg/blob/master/src/cg/generalize.js#L82). As features are not updated in layer source, style is NOT updated as well.

**Comment by Bulva** [comment]
Should be OK :-). Styles and aggregation of symbols looks ok with my local copy of mc-client. Please check it and close the issue.
