### ISSUE TITLE
NaN value in CombinedSymbol setBuffer method 

### ISSUE THREAD

**Issue by kordilery** [gis4dis/cg#15]
In CombinedSymbol, NaN value appears in maxValue variable if feature's array of values is shorter than the length given by date range - value_idx can overflow values lenght:
https://github.com/gis4dis/cg/blob/master/src/cg/symbolizers/CombinedSymbol.js#L139

And it looks like at least in this case value_index_shift is not taken into account, please check the documentation:
https://github.com/gis4dis/poster/wiki/Interface-between-MC-client-&-CG-v2#parameters

**Comment by Bulva** [comment]
Ok, I will check it

**Comment by kordilery** [comment]
@Bulva I'm going to work on the project today evening, so if you want me to explain you the issue properly, I'll be available at 6 PM on Hangouts. In this issue, I described the core cause I found when I was investigating the "Inconsistency in rightmost" bug , but I can show you how it happens.

**Comment by Bulva** [comment]
Ok, great.
