### ISSUE TITLE
Inconsistency in rightmost processing

### ISSUE THREAD

**Issue by jirik** [gis4dis/cg#17]
How to reproduce it:
- https://gis4dis-poster-master.g4d.sci.muni.cz/topics/drought/
- select date from 2019-05-19 to 2019-05-19
- click Play

**Comment by kordilery** [comment]
This is probably the consequence of [#15 ](consequence)

**Comment by Bulva** [comment]
I wish it were true because the worst option is the problem with jsts.

**Comment by jirik** [comment]
It seems to be related to JSTS. Anyway, please try first to fix #15 and then check this one again.

**Comment by Bulva** [comment]
Related to #15
