### ISSUE TITLE
Symbols are not aggregating when changing zoom level

### ISSUE THREAD

**Issue by jirik** [gis4dis/cg#18]
![image](https://user-images.githubusercontent.com/2271850/58160600-136b4a00-7c7f-11e9-812e-6032b4224cf4.png)

**Comment by kordilery** [comment]
I think this might be a problem of mc-client, currently it does not call generalize on resolution change...

**Comment by jirik** [comment]
@kordilery Is there any reason for not calling the generalize function on resolution change?

**Comment by kordilery** [comment]
I don't think there is any reason, only as it was not necessary to do it in the past:-) I can try to implement it tonight.

**Comment by kordilery** [comment]
I have it on my TODO list for a "while" - see [#11](https://github.com/gis4dis/mc-client/issues/11) :-D

**Comment by Bulva** [comment]
@kordilery Let me know if it works correctly 🤞

**Comment by kordilery** [comment]
@Bulva I think the aggregation can be tested right now by following steps:
1. changing zoom level
2. changing property to any other property
3. changing property to previous property

In the case of property change, generalize method is called and one of the parameter is current resolution.

The issue on the mc-client is that it does not call generalize method in case only resolution was changed (user zoomed in/out).

**Comment by Bulva** [comment]
@kordilery 
Aggregation performance was improved (3dbf5705aadfe4cfd4435e6f44326b35c8c6b09e). I've tested with client and it looks OK. Maybe there are some minor bugs with aggregation but I am not sure now if there is a problem with aggregation or computing the buffer from resolution. I'll try to write some tests if I have some time.

I have to check if intersectedFeatures have only one level
