### ISSUE TITLE
It's terribly slow

### ISSUE THREAD

**Issue by jirik** [gis4dis/cg#19]
About 4 second per frame when click to play (e.g. 2019-05-06). Not sure when this problem appeared, but it wasn't so slow before (it used to be definitely under 1 second). I guess it's related to aggregation/interpolation.

**Comment by Bulva** [comment]
Uh really slow, probably problem with crossreferences. I'll check it

**Comment by Bulva** [comment]
After some performance tests I can confirm you were right, it's a problem with aggregation. I hope I will fix it soon.
